### ISSUE TITLE
Support for badge custom Durations

### ISSUE THREAD

**Issue by 117503445** [TwiN/gatus#367] opened 2022-11-16 03:19 UTC
### Describe the feature request

The Durations of badge can be customized by the user instead of a predefined set of values(7d, 24h, 1h).

### Why do you personally want this feature to be implemented?

Currently badge only supports 7d, 24h, 1h as Durations, however, I would like to use 3 months Durations as a metric for application availability.

### How long have you been using this project?

2 month

### Additional information

I am willing to implement this feature. My expected user input might be 2h, 1d, 3m, 1y etc.
In the code implementation, the main modification is the calculation of the `from` variable, in `controller/handler/badge.go UptimeBadge()`.

**Comment by alexis974** [comment] 2022-11-18 13:06
I agree with @117503445  !

Furthermore, it would be pretty helpful to have the information of availability in a year which can be used as an SLI (service level indicator).

**Comment by TwiN** [comment] 2022-11-18 13:14
This is kind of a duplicate of #128 - comment on the issue and re act with 👍if you want it to be prioritized :)

**Closed** 2022-11-18 13:15 UTC
Labels: duplicate
