### ISSUE TITLE
feat: Sort by failed endpoints first

### ISSUE THREAD

**Issue by yuvals41** [TwiN/gatus#377] opened 2022-11-24 15:03 UTC
### Describe the feature request

hello,
when i view the ui dashboard i want to see the failed responses pop up at the top of the page where i can see the error on which endpoint instead of scrolling down (we have a lot of endpoints) until we find our failed endpoint.

to summerize we want the failed services to always be on top of the page

### Why do you personally want this feature to be implemented?

we need a good view if our services are down so can figure it out quickly instead of scrolling down until we find if there is an issue

### How long have you been using this project?

1 week

**Comment by TwiN** [comment] 2022-11-24 19:05
Duplicate of #150

**Closed by TwiN** 2022-11-24 19:05 UTC
