### ISSUE TITLE
multiple gatus backends in kubernetes behind single ingress

### ISSUE THREAD

**Issue by eckra** [TwiN/gatus#251] opened 2022-02-09 18:01 UTC
I'm trying to setup separate backends for different checks (to load balance the checks) but unable to setup an ingress with multiple paths because the gatus backend redirects to the base url.

gatus.example.com/ -> gatus backend 1
gatus.example.com/ping/ -> gatus backend 2

I've tried a lot of ingress tricks to get the redirects to work properly, but no luck. If I could set a base-url in the gatus config, then the redirects could be properly sent to the correct endpoint.

**Comment by TwiN** [comment] 2022-02-10 03:22
Duplicate of #88

**Closed by TwiN** 2022-02-10 03:22 UTC
Labels: duplicate
