### ISSUE TITLE
Support OpenID Connect for auth 

### ISSUE THREAD

**Issue by mTLamouchi** [TwiN/gatus#205] opened 2021-11-23 11:52 UTC
How  I can secure the gatus api with open id connect, any suggestion for good openId libraries in golang

**Comment by TwiN** [comment] 2021-12-15 02:56
I'd love to add support for OIDC, alas, I've barely ever played with OAuth2, much less OpenID.

**Comment by TwiN** [comment] 2021-12-16 23:01
Duplicate of #158

**Closed by TwiN** 2021-12-16 23:01 UTC
Labels: feature

**Comment by TwiN** [comment] 2022-01-09 01:36
Released in [v3.5.0](https://github.com/TwiN/gatus/releases/tag/v3.5.0)

**Comment by xeruf** [comment] 2022-10-30 22:34
See:
- https://twin.sh/articles/56/securing-gatus-with-oidc-using-auth0
- https://github.com/TwiN/gatus#oidc

You should link to the readme from gatus.io as it took me a while to locate the documentation there ^^
