### ISSUE TITLE
Data retention

### ISSUE THREAD

**Issue by xoraingroup** [TwiN/gatus#137] opened 2021-07-13 04:07 UTC
Is there any switch or configuration to configure gatus for data retention when storing data in file?  

Like data_retention: 30d / 4d etc

**Comment by TwinProduction** [comment] 2021-07-13 23:36
Hello @xoraingroup, that setting doesn't currently exists, but since v2.1.0, I have started making modifications to support a longer result history, and considering the database storage implementation I'm currently working on, it shouldn't be long before this feature will be added.

**Comment by xoraingroup** [comment] 2021-07-14 03:46
Awesome as always. Thank you :)

**Comment by TwiN** [comment] 2021-11-20 20:43
Duplicate of #128

**Closed by TwiN** 2021-11-20 20:43 UTC
Labels: duplicate, question
