### ISSUE TITLE
Request Header Fields Too Large

### ISSUE THREAD

**Issue by antikilahdjs** [TwiN/gatus#674] opened 2024-02-07 12:45 UTC
### Describe the bug

I have a small monitors like 6. The all alerts is so simple like the screenshot below. To works I need restart the Gatus each 10 minutes due the error "[api.ErrorHandler] Request Header Fields Too Large"

![image](https://github.com/TwiN/gatus/assets/33559260/9e725cb4-be53-4ec0-8d3c-e01e9cc9878a)

### What do you see?

[api.ErrorHandler] Request Header Fields Too Large

![image](https://github.com/TwiN/gatus/assets/33559260/77149fa8-7489-4648-9c6e-6feffd1e7a55)

### What do you expect to see?

I don't remember but some version in the past I never got this error but now I am not able to say that version

### List the steps that must be taken to reproduce this issue

1. Just install using normal way
2. In my case my monitors came from Prometheus like that http://thanos-query-frontend.thanos:9090/api/v1/query?query=sum%28avg_over_time%28xxxxxxxxx%7Bxxxxxxx%3D~%22.%2A%22%2C%20xxxxxx%3D~%22xxxxxxxxx%22%2C%20xxxxxx%21%3D%22xxxxxxxxx%22%7D%5B10m%5D%29%29%20by%20%28xxxxxxx%2C%20topic%29

***I guess the issue is the long URL because I tried to removed and the application run without any errors. There is possible fix it internally ? I need use the Prometheus Queries and almost time the URL is too long because I need convert it to works in Gatus as well

***** Update: It worked for some hours and the error back it again so, is not the issue with long URLs.

### Version

5.7.0

### Additional information

 2024/02/07 16:54:48 [watchdog][execute] Monitored group=Applications; endpoint=xxxx success=true; errors=0; duration=2ms

 2024/02/07 16:54:49 [watchdog][execute] Monitored group=Integrations; endpoint=xxxx; success=true; errors=0; duration=33ms

 2024/02/07 16:54:49 [watchdog][execute] Monitored group=Integrations; endpoint=xxxx; success=true; errors=0; duration=50ms

 2024/02/07 16:54:50 [watchdog][execute] Monitored group=API's; endpoint=xxxxx; success=true; errors=0; duration=13ms

 2024/02/07 16:54:51 [watchdog][execute] Monitored group=API's; endpoint=xxxxxx; success=true; errors=0; duration=42ms

 2024/02/07 16:54:52 [api.ErrorHandler] Request Header Fields Too Large

 2024/02/07 16:54:52 [api.ErrorHandler] Request Header Fields Too Large

 2024/02/07 16:54:54 [api.ErrorHandler] Request Header Fields Too Large

 2024/02/07 16:54:54 [api.ErrorHandler] Request Header Fields Too Large

**Comment by antikilahdjs** [comment] 2024-02-07 17:14
I just put double quota "URL:xxxx" and worked :(

**Comment by TwiN** [comment] 2024-02-07 22:27
This is a duplicate of #636, and there is already an open PR to fix this #663

As soon as @lifez has the opportunity to address my comment, I can merge the fix.

**Closed by TwiN** 2024-02-07 22:27 UTC
Labels: bug, duplicate

**Comment by antikilahdjs** [comment] 2024-02-08 19:50
Hello @TwiN .

I saw it but here I keep receiving the same error.

![image](https://github.com/TwiN/gatus/assets/33559260/e912974a-c001-4ecc-9625-fd3517ff5989)


 2024/02/08 19:47:47 [watchdog][execute] Monitored group=Applications; endpoint=xxxx; success=true; errors=0; duration=18ms

 2024/02/08 19:47:48 [api.ErrorHandler] Request Header Fields Too Large

 2024/02/08 19:47:48 [api.ErrorHandler] Request Header Fields Too Large

 2024/02/08 19:47:57 [watchdog][execute] Monitored group=Applications; endpoint=xxxx; success=true; errors=0; duration=2ms

**Comment by TwiN** [comment] 2024-02-09 03:13
@antikilahdjs Make sure you're using the latest image. It should work.

**Comment by antikilahdjs** [comment] 2024-02-09 13:21
@TwiN  thanks and I will try to use the latest image.

**Comment by TwiN** [comment] 2024-02-11 18:06
@antikilahdjs Let me know if it works out for you :eyes:

**Comment by antikilahdjs** [comment] 2024-02-11 18:10
Hello @TwiN . Using the latest image worked as a charm. Thank u so much

**Comment by TwiN** [comment] 2024-02-11 23:03
Glad to hear it!

**Comment by ashishpandey** [comment] 2024-03-01 02:45
We cannot use latest tag due to a policy constraint in our environment. Is there a plan to push this out in a versioned tag please? Can we help?
