### ISSUE TITLE
A separate trigger for checking the certificate expiration date.

### ISSUE THREAD

**Issue by danilvoe** [TwiN/gatus#247] opened 2022-02-06 11:37 UTC
### Describe the feature request

This feature is needed so that when the certificate validity trigger is triggered, Gatus can notify about problems that may occur and will reflect real problems with the service being checked.

Now Gatus will notify in 24 hours that there is a problem with the certificate, but if there is a real problem, for example, the HTTP status is 500, then Gatus will not notify. the trigger is already active. In essence, the certificate validity check should have the status of a warning trigger (with notification) and be colored yellow.

**Comment by TwiN** [comment] 2022-03-05 00:03
I think what you're asking for is the ability to specify a "severity" for a condition. For instance, you'd be able to specify whether the certificate being _about_ to expire should show as a warning (yellow) rather than a failure (red).

If I'm right, then this is a duplicate of #227

**Closed by TwiN** 2022-03-05 00:03 UTC
